project:
  type: website
  output-dir: docs

website:
  title: "Nkem Okweye | Portfolio"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: skills.qmd
        text: Skills
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article
